schema = {'$schema': 'http://json-schema.org/schema#',
 'type': 'object',
 'properties': {'user_id': {'type': ['null', 'string']},
  'name': {'type': 'string'},
  'email': {'type': 'string'},
  'instagram_handle': {'type': ['null', 'string']},
  'tiktok_handle': {'type': 'string'},
  'joined_at': {'type': 'string'},
  'advocacy_programs': {'type': 'array',
   'items': {'type': 'object',
    'properties': {'program_id': {'type': 'string'},
     'brand': {'type': ['integer', 'string']},
     'tasks_completed': {'type': 'array',
      'items': {'type': 'object',
       'properties': {'task_id': {'type': ['null', 'string']},
        'platform': {'type': ['integer', 'string']},
        'post_url': {'type': 'string'},
        'likes': {'type': ['integer', 'string']},
        'comments': {'type': ['integer', 'null']},
        'shares': {'type': 'integer'},
        'reach': {'type': 'integer'}},
       'required': ['comments',
        'likes',
        'platform',
        'post_url',
        'reach',
        'shares',
        'task_id']}},
     'total_sales_attributed': {'type': ['number', 'string']}},
    'required': ['brand',
     'program_id',
     'tasks_completed',
     'total_sales_attributed']}}},
 'required': ['advocacy_programs',
  'email',
  'instagram_handle',
  'joined_at',
  'name',
  'tiktok_handle',
  'user_id']}